### PR TITLE
Fix #1: Count vote twice on reply

### LINKED ISSUE #1: Vote counted twice on reply
A reply seems to be counted as a reply AND mention of the referenced author.

This results in two votes being applied by one reply

### PR DESCRIPTION
**Pull request by Smephite**
Replies seem to include mentions of the author replied to.

Removing the reply code will still count replies as a mention but will no longer count them as two votes.

Deleting the message will still result in a 'downvote' so no issue here.

### CODE REVIEW

**Comment by tyvdh** [comment]
Maybe the wrong place to comment on but should we ever be counting "downvotes". Not sure downvoting via delete is adding anything vs just greater complexity and disincentivizing the often right action of removing a comment that's either no longer needed or turns out to be unhelpful.

**Comment by Smephite** [comment]
> Maybe the wrong place to comment on but should we ever be counting "downvotes"? Not sure downvoting via delete is adding anything vs just greater complexity and disincentivizing the often right action of removing a comment that's either no longer needed or turns out to be unhelpful.

This is true, especially as deleting ones reply is almost never out of 'downvote'-reasons. After all we aren't count the replies a user is writing in order to help, but rather the replies a user is accumulating.

**Comment by MatejMecka** [comment]
One concern i have with Message deletion is a user using an alternate account to increase their votes by mentioning or replying to themselves and deleting the same message. With the current approach we're deleting the record. Instead of Deletion, perhaps we can add a new column deleted and maybe the message.content that we can use for processing later.

There's also with reacts the case where a user accidentally might give the reaction to the wrong person or simply misclick.

This are currently my concerns and if anyone has some ideas and suggestions feel free to leave them here: #4

**Review by MatejMecka — APPROVED** [review]
LGTM!

**Pull request merged**
