### PR TITLE
Unit Tests

### PR DESCRIPTION
**Pull request by w00kie**
Had to also refactor a lot of code to make it possible to test.

### CODE REVIEW

**Comment by w00kie** [comment]
Waiting on older PRs to merge before going ahead with this one.

**Comment by Smephite** [comment]
Looks really nice.

Maybe look into adding an github actions automation to automatically run those scripts on each pr?

**Comment by w00kie** [comment]
Alright, I think this is ready for prime time now.

**Review by Smephite — APPROVED** [review]
LGTM!

**Pull request merged**
