### PR TITLE
Clean up refactor

### PR DESCRIPTION
**Pull request by w00kie**
Moving all helpers into nice and tidy modules.

Also, use `pip-tools` to fix requirements.

### CODE REVIEW

**Review by MatejMecka — APPROVED** [review]
LGTM!

**Review by Smephite — APPROVED** [review]
So @MatejMecka let go of their single newline policy after all? :p

**Comment by Smephite** [comment]
Are you using any specific lint? Maybe we could add it as github action

**Comment by w00kie** [comment]
> Are you using any specific lint? Maybe we could add it as github action

This is `black` auto format with VSCode.

**Pull request merged**
